// ── SharePoint / Excel config ─────────────────────────────────────────────────
// Set EXCEL_URL to the direct download URL of your SharePoint Excel file.
//
// How to get the URL:
//   1. Go to SharePoint → open the Excel file
//   2. Share → Copy link (Anyone with the link can view)
//   3. Use the raw download form:
//      https://<tenant>.sharepoint.com/sites/<site>/_layouts/15/download.aspx?UniqueId=<file-guid>
//   OR use the file's REST endpoint:
//      https://<tenant>.sharepoint.com/sites/<site>/_api/web/GetFileByServerRelativeUrl('<path>')/$value
//
// Leave empty to use demo data.
export const EXCEL_URL = ''

// Power Automate HTTP trigger URL (recommended — works with org-authenticated SharePoint).
// Paste the URL from your flow's "When an HTTP request is received" trigger here.
// When set, this takes priority over EXCEL_URL.
export const POWER_AUTOMATE_URL = ''

// Sheet name in the Excel workbook (Microsoft Forms names it "Sheet1" by default)
export const EXCEL_SHEET = 'Sheet1'

// How often to re-pull from SharePoint (ms). 0 = only on page load.
export const POLL_INTERVAL_MS = 60_000 // 60 seconds

// ── Microsoft Form column → Case field mapping ─────────────────────────────────
// These must exactly match the question text in your Microsoft Form.
export const COLUMN_MAP = {
  id:              'ID',
  submittedAt:     'Start time',        // auto-generated by Forms — used as วันที่รับเรื่อง
  ifaName:         'ชื่อ IFA / Nickname',
  customer:        'ชื่อลูกค้า',
  accountNo:       'เลขที่บัญชีกองทุน',
  appointmentTime: 'เวลานัดติดต่อลูกค้า',
  transaction:     'ประเภทธุรกรรม',
  fund:            'กองทุน',
  fundOut:         'กองทุนที่ขายออก (สับเปลี่ยน)',
  fundIn:          'กองทุนที่ซื้อเข้า (สับเปลี่ยน)',
  amount:          'จำนวน',
  amountUnit:      'หน่วย',
  note:            'หมายเหตุ',
}
